global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:9090']

  # - job_name: 'node_exporter'
  #  static_configs:
  #    - targets: ['node_exporter:9100']

  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']

